[book]
authors = ["Amiya Behera"]
language = "en"
multilingual = false
src = "src"
title = "Iambrainstorming Blog"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/iambrainstorming/coding_blog"
